services:
  - type: web
    name: yoluxgo-platform
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: yoluxgo-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY  
        sync: false
      - key: SENDGRID_API_KEY
        sync: false

databases:
  - name: yoluxgo-db
    databaseName: yoluxgo
    user: yoluxgo
    plan: starter